"""Small HTML renderers for structured analysis cards."""
import html

def result_html(data):
    if not data: return "<div class='empty-state'><span class='empty-icon'>⌕</span><b>Nothing to review yet</b><span>Analyze a message to see its risk signals and next steps.</span></div>"
    score=data['risk_score']; level=html.escape(data['risk_level']); classes={"Low Risk":"low","Suspicious":"medium","High Risk":"high","Critical Scam Risk":"critical"}; tone=classes.get(data['risk_level'],'medium')
    types="".join(f"<span class='chip'>{html.escape(x)}</span>" for x in data['scam_types'])
    signals="".join(f"<li><span class='signal-check'>✓</span><span>{html.escape(x)}</span></li>" for x in data['signals']) or "<li><span class='signal-check neutral'>✓</span><span>No strong indicators detected</span></li>"
    actions="".join(f"<li><span class='action-index'>{i:02d}</span><span>{html.escape(item)}</span></li>" for i,item in enumerate(data['actions'],1))
    points="".join(f"<span>{html.escape(k.replace('_',' ').title())} <b>+{v}</b></span>" for k,v in data['signal_points'].items()) or "<span>No risk points triggered</span>"
    return f"""<section class='verdict {tone}'><div class='verdict-main'><div class='result-label'><span class='verdict-mark'>✓</span> SCAMSHIELD RISK ASSESSMENT</div><h2>{level}</h2><p class='verdict-summary'>{html.escape(data['explanation'])}</p><div class='verdict-meta'><span><small>DETECTED LANGUAGE</small><b>{html.escape(data['language'])}</b></span><span><small>MESSAGE TYPE</small><b>{types}</b></span></div></div><div class='score-wrap'><div class='score-gauge' style='--score:{score}' role='img' aria-label='Risk score {score} out of 100'><div class='gauge-center'><strong>{score}</strong><span>of 100</span></div></div><div class='score-caption'>RISK SCORE <span>· ADVISORY</span></div></div></section>
    <div class='result-grid'><article class='result-card signal-card'><div class='result-card-head'><span class='card-icon'>◎</span><div><div class='card-overline'>WHAT WE NOTICED</div><h3>Risk signals</h3></div></div><ul class='signal-list'>{signals}</ul></article><article class='result-card actions-card'><div class='result-card-head'><span class='card-icon'>↗</span><div><div class='card-overline'>YOUR NEXT STEP</div><h3>Recommended actions</h3></div></div><ol class='action-list'>{actions}</ol></article><article class='result-card safety-card'><div class='safety-icon'>✳</div><div><div class='card-overline'>KEEP IN MIND</div><h3>Safety tip</h3><p>{html.escape(data['safety_tip'])}</p></div></article></div>
    <details class='transparency'><summary><span class='transparency-icon'>i</span><span><b>How was this verdict generated?</b><small>See how the current MVP reached this result</small></span><span class='disclosure-arrow'>⌄</span></summary><div class='transparency-body'><p>Current MVP analysis uses explainable heuristic and language-aware risk detection. It does not use a trained scam-classification model. Risk score is not a calibrated probability.</p><div class='point-list'>{points}</div></div></details><p class='disclaimer'>Automated analysis cannot guarantee legitimacy. Verify unexpected messages independently.</p>"""
